/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Public API
 * OpenAPI spec version: 0.0.0
 */

export interface SignUpRequest {
  username: string;
  email: string;
  password: string;
}
