/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Public API
 * OpenAPI spec version: 0.0.0
 */
import type { SignUpRequest } from './signUpRequest';

export type SignUpCreateBody = {
  request: SignUpRequest;
};
