/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Private API
 * OpenAPI spec version: 0.0.0
 */
import type { CreateTodoRequest } from '../models'
import { privateInstance } from '../privateInstance'

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

export const getPrivateAPI = () => {
  const createTodo = (
    createTodoRequest: CreateTodoRequest,
    options?: SecondParameter<typeof privateInstance>,
  ) => {
    return privateInstance<void>(
      {
        url: `/api/private/todo`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: createTodoRequest,
      },
      options,
    )
  }

  return { createTodo }
}
export type CreateTodoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPrivateAPI>['createTodo']>>
>
