/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Private API
 * OpenAPI spec version: 0.0.0
 */
import type { CreateTodoRequest } from './createTodoRequest'

export type CreateTodoBody = {
  req: CreateTodoRequest
}
