openapi: 3.0.0
info:
  title: Private API
  version: 0.0.0
tags: []
paths:
  /api/private/todo:
    post:
      operationId: CreateTodo
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoRequest'
components:
  schemas:
    CreateTodoRequest:
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string
        description:
          type: string
