openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths:
  /api/public/signup:
    post:
      operationId: SignUp_create
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                request:
                  $ref: '#/components/schemas/SignUpRequest'
              required:
                - request
components:
  schemas:
    SignUpRequest:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
