// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Akito-Fujihara/web-application-template/app/adapter/server"
)

// Injectors from wire.go:

func InitializeServer() (*server.Application, error) {
	privateServer := server.NewPrivateServer()
	publicServer := server.NewPublicAServer()
	application := server.NewApplication(privateServer, publicServer)
	return application, nil
}
